### PR TITLE
getGitInfo: add URL output, related to #145

### PR DESCRIPTION
**Pull request by jjokella**
URL output into the build log file could be implemented like this.

Possible problem: If there is no remote named `origin` in the git repository, `git remote get-url origin` will lead to errors. (This will not happen very often, but it is an possible source of errors introduced by this code...)

### CODE REVIEW

**Comment by DCaviedesV** [comment]
This sounds like a good idea.
Indeed, if there is no origin (which I guess would typically mean someone inheriting non-versioned code), git returns a fatal error.
I would suggest to catch the error and print something meaningful, something like:
`git -C ${rootdir} remote get-url origin || echo "Origin not set" >> $logfile`
Writing into the `$logfile` seems to be missing too, isn't it?

**Comment by jjokella** [comment]
>  Writing into the `$logfile` seems to be missing too, isn't it?
I fixed these.

I was hesitant about adding the error catching via `||` , because I could not quickly find another place in the scripts, where this is done and I usually stay within the realm of syntax already used elsewhere.

I will add it now as well, but this will have to be tested I guess!

**Comment by niklaswr** [comment]
I tested this branch and added some fixes.  

In **summary**:  
-) There was a typo blocking the output to the logfile: `$logfile`-->`$log_file`  
-) The suggested git command had to be wrapped in an outer `echo` command. Otherwise the redirect operator `>>` is used in the ''or''-case only and the remote URL is not dumped to the logfile. `git -C ${rootdir} remote get-url origin || echo "Origin not set" >> $logfile` --> `echo "remote url: $(git -C ${rootdir} remote get-url origin || echo "Remote origin not set for TSMP")" >> $log_file` 
In addition I added some descriptions to individual git logs (`commit:`, `tag:`, etc).
-) Logging the used `branch` does lead to misleading output in case of a detached HEAD. Further logging the used `commit` should be more precise anyway so I changed to log the `commit` instead of the `branch`.
-) Just for the sake of completeness I added a check if the used model component is coming as a git-repo at all. Not even sure if nessecery, but its there.

All my test passed, but pleas do test this again before merging.

**Comment by jjokella** [comment]
Thanks Niklas, everything sounds good to me. If your tests run through, this should be merged, so I will do that.

**Pull request merged**
