### PR TITLE
Update MSA build interface for JUWELS/DEEP/JURECA

### PR DESCRIPTION
**Pull request by ivzhukov**
* Score-P support extended for DEEP and JUWELS
* Updated batch scripts
* Tested only on JUWELS

### CODE REVIEW

**Comment by joergbenke** [comment]
Stage 2022 works for all of the following combinations (build, setup, run):
- JUWELS (CPU, GPU)
- JURECA (CPU, GPU 
- DEEP (CPU, GPU)

It fails during runtime for JUWELS MSA with the following error message:
---------------------------------------------------------------
...
oasis_init_comp: Calling MPI_Init
[jwb0193:29702:0:29702] Caught signal 4 (Illegal instruction: illegal operand)
[jwb0193:29701:0:29701] Caught signal 4 (Illegal instruction: illegal operand)
[jwb0193:29704:0:29704] Caught signal 4 (Illegal instruction: illegal operand)
[jwb0193:29703:0:29703] Caught signal 4 (Illegal instruction: illegal operand)
==== backtrace (tid:  29703) ====
 0 0x0000000000012cf0 __funlockfile()  :0
 1 0x00000000007684ff mod_oasis_namcouple_mp_inipar_alloc_()  ???:0
 2 0x00000000007aa561 mod_oasis_namcouple_mp_oasis_namcouple_init_()  ???:0
 3 0x000000000074c151 mod_oasis_method_mp_oasis_init_comp_()  ???:0
 4 0x000000000070e4c0 oas_pfl_init_()  ???:0
 5 0x0000000000708d0b amps_Init()  ???:0
 6 0x000000000040dee4 main()  ???:0
 7 0x000000000003ad85 __libc_start_main()  ???:0
 8 0x000000000040ddbe _start()  ???:0
...
---------------------------------------------------------------------

Build: ./build_tsmp.ksh -v 3.1.0MCT -c clm-cos-pfl -m JUWELS -O Intel -A GPU (also with -A MSA)
Setup: ./setup_tsmp.ksh -v 3.1.0MCT -V cordex -m JUWELS -I _cordex -O Intel -A MSA -H 4

**Comment by ivzhukov** [comment]
did you build everything on JUWELS Booster? and submitted from the JUWELS Booster login nodes?

**Comment by joergbenke** [comment]
When building and doing the setup of TSMP on the JUWELS Booster login node then it works (in all cases eurocordex scenario).

**Comment by jjokella** [comment]
Hi all, 
I have merged `ivzhukov:msa_build_interface` into `TSMP_pdaf` and tried to compile with the following command
```
./build_tsmp.ksh -m JURECA -v 3.1.0MCTPDAF -O Intel -c clm-pfl
```
so JURECA, CPU with CLM, ParFlow and PDAF.

In the PDAF scripts I get an error (as expected, since they are not part of this PR):
```
ifort: error #10236: File not found:  '/p/software/jurecadc/stages/2022/software/imkl/2021.4.0-ipsmpi-2021b/mkl/lib/intel64/libmkl_intel_lp64.a'                                               
ifort: error #10236: File not found:  '/p/software/jurecadc/stages/2022/software/imkl/2021.4.0-ipsmpi-2021b/mkl/lib/intel64/libmkl_intel_thread.a'                                             
ifort: error #10236: File not found:  '/p/software/jurecadc/stages/2022/software/imkl/2021.4.0-ipsmpi-2021b/mkl/lib/intel64/libmkl_core.a'  
```

Just wanted to ask if you have any notes on these libraries - I will try also compiling without loading them (they are loaded explicitly)
https://github.com/HPSCTerrSys/TSMP/blob/da000745496c3e605c34f46e7d33c57b6c403fdc/bldsva/intf_DA/pdaf1_1/arch/JURECA/build_interface_pdaf1_1_JURECA.ksh#L34-L38

**Pull request merged**
