### PR TITLE
PDAF: solver_richards.c Saturation update

### LINKED ISSUE #139: TSMP-PDAF: `solver_richards.c`, is an update of saturations missing?
In some models an update of saturations/pressures seems to be missing and this is (apparently) fixed by including some lines in `solver_richards.c`.

I will open a corresponding Pull request and detail the changes to start a discussion whether they are correct.

### PR DESCRIPTION
**Pull request by jjokella**
Committed changes were found by diffing in a off-repository version of TSMP-PDAF. The user of this version found that his TSMP-PDAF simulations, and specifically updates went from very bad (immediately back at pre-update values) to very good (gradually approaching observations), when the lines  from the commits were added in `solver_richards.c`.

Therefore, it is worth checking whether the lines should be added in `TSMP_pdaf`.

However, I have not completely understood the changes - they originate from un-tracked versions of TSMP.

Idea: The lines should update saturations according to the PDAF result.

Resolves #139

### CODE REVIEW

**Comment by kvrigor** [comment]
This change seems out of place. Saturation should be already updated in two places:

* at `SetupRichards()`

https://github.com/HPSCTerrSys/TSMP/blob/4c5ae46042a2c698688c4a4e06d8c693e47335d3/bldsva/intf_DA/pdaf1_1/tsmp/parflow3_9/solver_richards.c#L1170-L1174

* at `AdvanceRichards()`

https://github.com/HPSCTerrSys/TSMP/blob/4c5ae46042a2c698688c4a4e06d8c693e47335d3/bldsva/intf_DA/pdaf1_1/tsmp/parflow3_9/solver_richards.c#L2944-L2947

Can we find the commit info associated with the original change? `git blame` may help to discover the original commit.

**Comment by DCaviedesV** [comment]
is this still alive?

**Comment by jjokella** [comment]
This would need further input from ParFlow-experts.

I am very hesitant to change this part as it may change model behavior.

**Comment by jjokella** [comment]
Revisiting the problem and thanks to @kvrigor mentioning the misplacement of the saturation update, I currently think that the saturation-update-fix (if applicable) should be in the `update_parflow`:
https://github.com/HPSCTerrSys/TSMP/blob/b6a34f3e2aec1fcd63dd4d94c5b14effef2ad4b9/bldsva/intf_DA/pdaf1_1/model/parflow/enkf_parflow.c#L796-L828

Here, the update saturations from the assimilation are used to update state variables for the next ParFlow forward simulation according to `pf_updateflag`. This flag is an input described in the Manual: https://hpscterrsys.github.io/TSMP/content/input_enkfpf.html#pf-updateflag

Notice that not actual update of saturations is performed. Instead, pressure values are updated. The change of this PR would update saturations explicitly.

**Comment by jjokella** [comment]
Closing this PR as the update of saturations has to be handled in the PDAF interface.

**Pull request closed without merging**
