### PR TITLE
GPU: Move `module load CUDA` to loadenvs scripts

### PR DESCRIPTION
**Pull request by jjokella**
Updated the `loadenvs` files for JUWELS and JURECA to `Stages/2022` and saved the files for `Stages/2020` for later reference.

The changes still need to be tested.

### CODE REVIEW

**Comment by kvrigor** [comment]
I tried to build TSMP and then I encountered a compile error at ParFlow. I think you're already aware of this:

```
../TSMP/parflow3_9_JURECA_3.1.0MCT_clm-pfl/pfsimulator/parflow_lib/advect.F(266): error #6211: A
 symbol must be a defined parameter in this context.   [I]                                      
               stop(i,j)   =                                                                    
```

This is a known [issue](https://github.com/parflow/parflow/issues/355) which has already been fixed in ParFlow 3.10. We need to update the ParFlow `build_interface_*` scripts again, which is a pain since the version is hardcoded in the filenames. Should we fix the ParFlow naming once and for all? I suggest we make the version generic by renaming `parflow3_9 -> parflowX_Y`.

**Comment by jjokella** [comment]
@kvrigor  I agree that we should make the parflow-directories verison-independent. My suggestion would be to remove the old `parflow` directories and replace them with the current versions: https://github.com/HPSCTerrSys/TSMP/issues/127

**Comment by jjokella** [comment]
Using ParFlow version 3.10, I still run into an error building TSMP while compiling ParFlow:
```
/p/software/juwels/stages/2022/software/CUDA/11.5/targets/x86_64-linux/include/cub/util_namespace.cuh:46:2: error: #error CUB requires a definition of CUB_NS_QUALIFIER when CUB_NS_PREFIX/POSTFIX are defined.
   46 | #error CUB requires a definition of CUB_NS_QUALIFIER when CUB_NS_PREFIX/POSTFIX are defined. 
      |  ^~~~~
make[2]: *** [pfsimulator/parflow_lib/CMakeFiles/pfsimulator.dir/build.make:104: pfsimulator/parflow_lib/CMakeFiles/pfsimulator.dir/axpy.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1623: pfsimulator/parflow_lib/CMakeFiles/pfsimulator.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by kvrigor** [comment]
> ```
> /p/software/juwels/stages/2022/software/CUDA/11.5/targets/x86_64-linux/include/cub/util_namespace.cuh:46:2: error: #error CUB requires a definition of CUB_NS_QUALIFIER when CUB_NS_PREFIX/POSTFIX are defined.
>    46 | #error CUB requires a definition of CUB_NS_QUALIFIER when CUB_NS_PREFIX/POSTFIX are defined. 
>       |  ^~~~~
> make[2]: *** [pfsimulator/parflow_lib/CMakeFiles/pfsimulator.dir/build.make:104: pfsimulator/parflow_lib/CMakeFiles/pfsimulator.dir/axpy.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:1623: pfsimulator/parflow_lib/CMakeFiles/pfsimulator.dir/all] Error 2
> make: *** [Makefile:146: all] Error 2
> ```

I can't reproduce this error.. here's how I built TSMP: `./build_tsmp.ksh -v 3.1.0MCT -c clm-pfl -m JUWELS -O Intel` 

[log_all_270422-112808.txt](https://github.com/HPSCTerrSys/TSMP/files/8571482/log_all_270422-112808.txt)

**Comment by jjokella** [comment]
> > ```
> > /p/software/juwels/stages/2022/software/CUDA/11.5/targets/x86_64-linux/include/cub/util_namespace.cuh:46:2: error: #error CUB requires a definition of CUB_NS_QUALIFIER when CUB_NS_PREFIX/POSTFIX are defined.
> >    46 | #error CUB requires a definition of CUB_NS_QUALIFIER when CUB_NS_PREFIX/POSTFIX are defined. 
> >       |  ^~~~~
> > make[2]: *** [pfsimulator/parflow_lib/CMakeFiles/pfsimulator.dir/build.make:104: pfsimulator/parflow_lib/CMakeFiles/pfsimulator.dir/axpy.cpp.o] Error 1
> > make[1]: *** [CMakeFiles/Makefile2:1623: pfsimulator/parflow_lib/CMakeFiles/pfsimulator.dir/all] Error 2
> > make: *** [Makefile:146: all] Error 2
> > ```
> 
> I can't reproduce this error.. here's how I built TSMP: `./build_tsmp.ksh -v 3.1.0MCT -c clm-pfl -m JUWELS -O Intel`
> 
> [log_all_270422-112808.txt](https://github.com/HPSCTerrSys/TSMP/files/8571482/log_all_270422-112808.txt)

The error happens when compiling with `-A GPU` I think. Maybe you can try again with `./build_tsmp.ksh -v 3.1.0MCT -c clm-pfl -m JUWELS -O Intel -A GPU`?

**Comment by kvrigor** [comment]
> Using ParFlow version 3.10, I still run into an error building TSMP while compiling ParFlow:
> 
> ```
> /p/software/juwels/stages/2022/software/CUDA/11.5/targets/x86_64-linux/include/cub/util_namespace.cuh:46:2: error: #error CUB requires a definition of CUB_NS_QUALIFIER when CUB_NS_PREFIX/POSTFIX are defined.
>    46 | #error CUB requires a definition of CUB_NS_QUALIFIER when CUB_NS_PREFIX/POSTFIX are defined. 
>       |  ^~~~~
> make[2]: *** [pfsimulator/parflow_lib/CMakeFiles/pfsimulator.dir/build.make:104: pfsimulator/parflow_lib/CMakeFiles/pfsimulator.dir/axpy.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:1623: pfsimulator/parflow_lib/CMakeFiles/pfsimulator.dir/all] Error 2
> make: *** [Makefile:146: all] Error 2
> ```

This error has just been [fixed](https://github.com/parflow/parflow/commit/dd1cd2482bb0a1ddfd88e31d9d657364f1551255) in ParFlow `master`. You may retry compiling @jjokella (don't forget to checkout ParFlow `master` branch)

**Review by s-poll — CHANGES_REQUESTED** [review]
It seems better to test Stages/2022 and Parflow v3.11 extensively before making it the default. Can we put the new environment file better in a separate loadenvs.Intel_2022 / loadenvs.Gnu_2022  and source that with -O Intel_2022 / Gnu_2022? Thus, we would include both options and could easily switch the default in the next version. The renaming of `parflow3_9` to a generic `parflow` has been done in #127.

**Comment by kvrigor** [comment]
I've merged the latest changes from `master` and switched back the default to `Stages/2020`. Please try @s-poll if you can successfully build and run a case

**Comment by kvrigor** [comment]
Update: Model runs using GPU fail with error `CUDA Error (yaksuri_cuda_init_hook:src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c,114): no CUDA-capable device is detected` . The cause is still being investigated.

**Comment by s-poll** [comment]
Is the cause of the issue with the GPU version in combination with stg2022 still under investigation?

In case it is not easy fixable, we could have stg2020 (default) and stg2022 in parallel. The use of different stages without addition duplications in the src shell be working with the mean of `${compiler%%[_,.]*}` instead of `$compiler` in [JURECA arch build](https://github.com/HPSCTerrSys/TSMP/blob/master/bldsva/intf_oas3/clm3_5/arch/JURECA/build_interface_clm3_5_JURECA.ksh#L34-L36) and [JUWELS arch build](https://github.com/HPSCTerrSys/TSMP/blob/master/bldsva/intf_oas3/clm3_5/arch/JUWELS/build_interface_clm3_5_JUWELS.ksh#L34-L36). This would also (partly) solve the additional duplicity mentioned in #144.

**Comment by DCaviedesV** [comment]
@jjokella can you check how this PR overlaps with the [msa_build_interface branch](https://github.com/HPSCTerrSys/TSMP/tree/msa_build_interface)? We discussed that there may be some substantial overlap. Perhaps it is worth merging with [msa_build_interface branch](https://github.com/HPSCTerrSys/TSMP/tree/msa_build_interface) prior to pulling into the master?

**Comment by jjokella** [comment]
@DCaviedesV I have updated both `master-134` and `msa_build_interface` to be up-to-date with `master` (hope that was alright).

A comparison lead me to the conclusion that the addition from this PR would be that the somewhat ill-placed `module load CUDA` commands in the build scripts are tried to be incorporated in the `loadenvs` files. (example here for `JURECA`)
https://github.com/HPSCTerrSys/TSMP/blob/66bdaef86f522ccd254bf83d9195fe6239699079/bldsva/intf_oas3/parflow/arch/JURECA/build_interface_parflow_JURECA.ksh#L66-L68

This would have to be tested and could be interesting, but I was kind of on the sidelines from the second half of the implementations by @s-poll  ad @kvrigor 

I would advice for merging `msa_build_interface` and then try to make this PR compatible in a second step.

**Comment by jjokella** [comment]
I renamed the PR for its title to more accurately reflect its update to other developments.

**Comment by DCaviedesV** [comment]
This is a sound approach. Did you by any chance test the merged `msa_build_interface`? I was on my way to do this when I got the notification.

**Comment by kvrigor** [comment]
> I would advice for merging `msa_build_interface` and then try to make this PR compatible in a second step.

I agree. Also this effort seems to be superseded by #156; feel free to close this PR if appropriate.

I got stuck with the `CUDA error: no CUDA-capable device is detected` when running the CORDEX case with GPU-built ParFlow. I'm not sure if `Stages/2023` has the same issue.

**Comment by jjokella** [comment]
Closing this PR, downgrading it to a PR, as I believe it would be best if someone looks at the `module load` command with a fresh view in the `release_candidate`. See #186

**Pull request closed without merging**
